### ISSUE TITLE
Does not work for 1.11

### ISSUE THREAD

**Issue by wgaylord** [ProjectTestificate/MinecraftMappings#4]
Throws 

`Traceback (most recent call last):
  File "genmappings.py", line 122, in <module>
    spigot_mappings = spigot.download_mappings(build_data_commit)
  File "C:\Users\chibi\Downloads\MinecraftMappings\spigot.py", line 35, in download_mappings
    classes = srg.parser.parse_compact_lines(lines)
  File "C:\Users\chibi\Downloads\MinecraftMappings\srg\parser.py", line 108, in parse_compact_lines
    renamed = types.parse_internal_name(renamed_name)
  File "C:\Users\chibi\Downloads\MinecraftMappings\srg\types.py", line 232, in parse_internal_name
    return parse_name(name.replace("/", "."))
  File "C:\Users\chibi\Downloads\MinecraftMappings\srg\types.py", line 262, in parse_name
    raise ValueError("Couldn't parse name " + name)
ValueError: Couldn't parse name ServerStatisticManager#`

**Comment by Techcable** [comment]
I assumed no one would be insane enough to put '#' in a class name :roll_eyes: Guess i'll have to fix it.

**Comment by wgaylord** [comment]
It looks like a derp as the line it is in in the srg has the same line with
out the # above it.

**Comment by wgaylord** [comment]
I patched it on my end  (Basically made it after replacing all # with nothing)

So now forgedbukkit can get rolling on 1.11 and 1.10.2

**Comment by wgaylord** [comment]
Closing this as it's no longer valid.
